"""The 100 sed drill problems.

Each problem's `answer` is exactly what a user would type after `sed `
on a real command line (quoting included), e.g. "-n '2,4p'".
The expected output is computed at run time by executing `answer`
against `input`, so correctness never depends on hand-transcribed text.
"""

PROBLEMS = [
    # --- 1. 置換の基礎 (s command) ---------------------------------
    {
        "id": 1, "category": "置換の基礎", "difficulty": 1,
        "title": "基本の置換",
        "description": "文字列 \"foo\" を \"bar\" に置き換えてください（最初に見つかった1箇所だけでよい）。",
        "input": "foo bar foo\n",
        "answer": r"'s/foo/bar/'",
        "hint": "s/検索文字列/置換文字列/ が基本形です。",
    },
    {
        "id": 2, "category": "置換の基礎", "difficulty": 1,
        "title": "すべて置換 (gフラグ)",
        "description": "行内のすべての \"foo\" を \"bar\" に置き換えてください。",
        "input": "foo bar foo\n",
        "answer": r"'s/foo/bar/g'",
        "hint": "末尾に g フラグを付けると行内すべてに効きます。",
    },
    {
        "id": 3, "category": "置換の基礎", "difficulty": 1,
        "title": "大文字小文字を無視した置換 (Iフラグ)",
        "description": "大文字・小文字を区別せずに \"hello\" を \"hi\" に置き換えてください（すべて）。",
        "input": "Hello HELLO hello\n",
        "answer": r"'s/hello/hi/gI'",
        "hint": "I フラグ（大文字のi）で大文字小文字を無視できます。",
    },
    {
        "id": 4, "category": "置換の基礎", "difficulty": 1,
        "title": "N番目だけ置換",
        "description": "行内で3番目に出現する \"a\" だけを \"b\" に置き換えてください。",
        "input": "a a a a a\n",
        "answer": r"'s/a/b/3'",
        "hint": "s///N のように数字を指定すると N 番目だけ置換できます。",
    },
    {
        "id": 5, "category": "置換の基礎", "difficulty": 1,
        "title": "N番目以降をすべて置換",
        "description": "3番目以降に出現する \"x\" をすべて \"y\" に置き換えてください。",
        "input": "x x x x x\n",
        "answer": r"'s/x/y/3g'",
        "hint": "Ng の形（数字の後にg）で N 番目以降すべてに効きます。",
    },
    {
        "id": 6, "category": "置換の基礎", "difficulty": 1,
        "title": "マッチ文字列を再利用 (&)",
        "description": "\"cat\" を大かっこで囲んでください（例: \"cat\" → \"[cat]\"）。& を使いましょう。",
        "input": "cat dog\n",
        "answer": r"'s/cat/[&]/'",
        "hint": "置換文字列の中で & はマッチした文字列全体を表します。",
    },
    {
        "id": 7, "category": "置換の基礎", "difficulty": 1,
        "title": "区切り文字の変更",
        "description": "パス中の \"/usr\" を \"/opt\" に置き換えてください。スラッシュが多いので区切り文字を変えると書きやすくなります。",
        "input": "/usr/local/bin\n",
        "answer": r"'s|/usr|/opt|'",
        "hint": "s の区切り文字はスラッシュ以外（| や # など）にも変更できます。",
    },
    {
        "id": 8, "category": "置換の基礎", "difficulty": 1,
        "title": "複数の置換を一度に",
        "description": "\"foo\" を \"baz\" に、\"bar\" を \"qux\" にそれぞれ置き換えてください。",
        "input": "foo bar\n",
        "answer": r"-e 's/foo/baz/' -e 's/bar/qux/'",
        "hint": "-e オプションを複数回使うと、複数のスクリプトを順番に適用できます。",
    },
    {
        "id": 9, "category": "置換の基礎", "difficulty": 1,
        "title": "連続する空白を1つに",
        "description": "連続する空白を1つのスペースにまとめてください。",
        "input": "a   b    c\n",
        "answer": r"'s/ \+/ /g'",
        "hint": "空白1文字以上にマッチする正規表現は ' \\+' です（GNU拡張）。",
    },
    {
        "id": 10, "category": "置換の基礎", "difficulty": 1,
        "title": "行頭に文字を追加",
        "description": "各行の先頭に \">> \" を追加してください。",
        "input": "hello world\n",
        "answer": r"'s/^/>> /'",
        "hint": "置換元を ^ （行頭の空文字列）にすると先頭に追加できます。",
    },
    {
        "id": 11, "category": "置換の基礎", "difficulty": 1,
        "title": "行末に文字を追加",
        "description": "各行の末尾に \" <<\" を追加してください。",
        "input": "hello world\n",
        "answer": r"'s/$/ <</'",
        "hint": "置換元を $ （行末の空文字列）にすると末尾に追加できます。",
    },
    {
        "id": 12, "category": "置換の基礎", "difficulty": 1,
        "title": "タブをスペースに変換",
        "description": "タブ文字をすべて1個のスペースに置き換えてください。",
        "input": "a\tb\tc\n",
        "answer": r"'s/\t/ /g'",
        "hint": "タブ文字は正規表現内で \\t と書けます（GNU拡張）。",
    },
    {
        "id": 13, "category": "置換の基礎", "difficulty": 1,
        "title": "単語の削除",
        "description": "\"quick \" という部分文字列を削除してください（sで空文字に置換）。",
        "input": "the quick brown fox\n",
        "answer": r"'s/quick //'",
        "hint": "置換後の文字列を空にすれば、その部分を削除したことになります。",
    },
    {
        "id": 14, "category": "置換の基礎", "difficulty": 1,
        "title": "区切り文字の置き換え",
        "description": "カンマを \" and \" に置き換えてください。",
        "input": "apple,banana\n",
        "answer": r"'s/,/ and /'",
        "hint": "検索対象がメタ文字でなければそのまま書けます。",
    },
    {
        "id": 15, "category": "置換の基礎", "difficulty": 1,
        "title": "前後の空白を除去して整形",
        "description": "行頭・行末の余分な空白を削除し、単語間の連続空白を1つにまとめてください。",
        "input": "   hello   world   \n",
        "answer": r"-e 's/^ *//' -e 's/ *$//' -e 's/ \+/ /g'",
        "hint": "-e を複数回使い、行頭の空白削除・行末の空白削除・連続空白の圧縮を順に行います。",
    },

    # --- 2. 行の削除 (d command) ------------------------------------
    {
        "id": 16, "category": "行の削除", "difficulty": 1,
        "title": "特定行を削除 (行番号)",
        "description": "2行目を削除してください。",
        "input": "line1\nline2\nline3\n",
        "answer": r"'2d'",
        "hint": "行番号を直接指定して d コマンドを使います。",
    },
    {
        "id": 17, "category": "行の削除", "difficulty": 1,
        "title": "最終行を削除",
        "description": "最終行を削除してください（$ を使う）。",
        "input": "line1\nline2\nline3\n",
        "answer": r"'$d'",
        "hint": "$ は最終行を表すアドレスです。",
    },
    {
        "id": 18, "category": "行の削除", "difficulty": 1,
        "title": "範囲指定で削除",
        "description": "2行目から4行目までを削除してください。",
        "input": "1\n2\n3\n4\n5\n",
        "answer": r"'2,4d'",
        "hint": "start,end の形でアドレス範囲を指定できます。",
    },
    {
        "id": 19, "category": "行の削除", "difficulty": 1,
        "title": "パターンに一致する行を削除",
        "description": "\"DEBUG\" を含む行を削除してください。",
        "input": "INFO start\nDEBUG detail\nINFO end\n",
        "answer": r"'/DEBUG/d'",
        "hint": "/pattern/ の形でパターンにマッチする行を指定できます。",
    },
    {
        "id": 20, "category": "行の削除", "difficulty": 1,
        "title": "空行を削除",
        "description": "空行をすべて削除してください。",
        "input": "a\n\nb\n\n\nc\n",
        "answer": r"'/^$/d'",
        "hint": "空行は正規表現 ^$ にマッチします。",
    },
    {
        "id": 21, "category": "行の削除", "difficulty": 1,
        "title": "否定条件での削除",
        "description": "\"KEEP\" を含まない行をすべて削除してください（! を使う）。",
        "input": "KEEP this\ndrop this\nKEEP that\n",
        "answer": r"'/KEEP/!d'",
        "hint": "アドレスの直後に ! を付けると条件を否定できます。",
    },
    {
        "id": 22, "category": "行の削除", "difficulty": 1,
        "title": "先頭N行を削除",
        "description": "先頭3行を削除してください。",
        "input": "1\n2\n3\n4\n5\n",
        "answer": r"'1,3d'",
        "hint": "1,N の範囲指定で先頭N行を選べます。",
    },
    {
        "id": 23, "category": "行の削除", "difficulty": 1,
        "title": "特定行以降をすべて削除",
        "description": "3行目以降をすべて削除してください。",
        "input": "1\n2\n3\n4\n5\n",
        "answer": r"'3,$d'",
        "hint": "N,$ の範囲指定でN行目以降すべてを選べます。",
    },
    {
        "id": 24, "category": "行の削除", "difficulty": 1,
        "title": "先頭行を削除",
        "description": "先頭行（ヘッダー行）を削除してください。",
        "input": "header\ndata1\ndata2\n",
        "answer": r"'1d'",
        "hint": "1d で先頭行だけを削除できます。",
    },
    {
        "id": 25, "category": "行の削除", "difficulty": 1,
        "title": "コメント行の削除",
        "description": "\"#\" で始まるコメント行を削除してください。",
        "input": "# comment\nvalue=1\n# another comment\nvalue=2\n",
        "answer": r"'/^#/d'",
        "hint": "行頭が # であることは ^# で判定できます。",
    },

    # --- 3. 出力制御 (p / -n) ---------------------------------------
    {
        "id": 26, "category": "出力制御", "difficulty": 2,
        "title": "-n と p の基本",
        "description": "-n オプションと p コマンドを使い、2行目だけを出力してください。",
        "input": "1\n2\n3\n",
        "answer": r"-n '2p'",
        "hint": "-n オプションで自動出力を止め、p で明示的に出力したい行だけ表示します。",
    },
    {
        "id": 27, "category": "出力制御", "difficulty": 2,
        "title": "範囲を表示",
        "description": "-n を使い、2〜4行目だけを表示してください。",
        "input": "1\n2\n3\n4\n5\n",
        "answer": r"-n '2,4p'",
        "hint": "-n と範囲アドレス 2,4 を組み合わせます。",
    },
    {
        "id": 28, "category": "出力制御", "difficulty": 2,
        "title": "パターン一致行のみ表示 (grep相当)",
        "description": "-n を使い、\"ERROR\" を含む行だけを表示してください。",
        "input": "INFO ok\nERROR fail\nINFO ok2\nERROR fail2\n",
        "answer": r"-n '/ERROR/p'",
        "hint": "-n と /pattern/p を組み合わせるとgrepのように使えます。",
    },
    {
        "id": 29, "category": "出力制御", "difficulty": 2,
        "title": "最終行のみ表示",
        "description": "-n を使い、最終行だけを表示してください。",
        "input": "a\nb\nc\n",
        "answer": r"-n '$p'",
        "hint": "-n と $p で最終行だけ表示できます。",
    },
    {
        "id": 30, "category": "出力制御", "difficulty": 2,
        "title": "置換結果だけを表示",
        "description": "-n と s///p を使い、\"cat\" を含む行だけを \"dog\" に置換して表示してください。",
        "input": "cat food\nbird seed\ncat toy\n",
        "answer": r"-n 's/cat/dog/p'",
        "hint": "s///p のように置換コマンドにpフラグを付けると、置換した行だけ表示できます（-nと併用）。",
    },
    {
        "id": 31, "category": "出力制御", "difficulty": 2,
        "title": "行の二重出力",
        "description": "（-n を付けずに）2行目だけをもう一度、合計2回出力してください。",
        "input": "1\n2\n3\n",
        "answer": r"'2p'",
        "hint": "-n なしで p を使うと、その行が2回出力されます（自動出力+p分）。",
    },
    {
        "id": 32, "category": "出力制御", "difficulty": 2,
        "title": "奇数行のみ表示",
        "description": "-n とステップアドレス (~) を使い、1行目から2行おきに表示してください（奇数行）。",
        "input": "1\n2\n3\n4\n5\n6\n",
        "answer": r"-n '1~2p'",
        "hint": "1~2 は「1行目から2行おき」を意味するGNU拡張のステップアドレスです。",
    },
    {
        "id": 33, "category": "出力制御", "difficulty": 2,
        "title": "偶数行のみ表示",
        "description": "-n とステップアドレス (~) を使い、2行目から2行おきに表示してください（偶数行）。",
        "input": "1\n2\n3\n4\n5\n6\n",
        "answer": r"-n '2~2p'",
        "hint": "2~2 は「2行目から2行おき」を意味します。",
    },
    {
        "id": 34, "category": "出力制御", "difficulty": 2,
        "title": "否定でのパターン抽出",
        "description": "-n を使い、\"skip\" を含まない行だけを表示してください。",
        "input": "keep1\nskip this\nkeep2\nskip that\n",
        "answer": r"-n '/skip/!p'",
        "hint": "/pattern/!p のように ! で否定できます。",
    },
    {
        "id": 35, "category": "出力制御", "difficulty": 2,
        "title": "複数範囲を表示",
        "description": "-n を使い、1行目と最終行の両方を表示してください。",
        "input": "first\nmid1\nmid2\nlast\n",
        "answer": r"-n -e '1p' -e '$p'",
        "hint": "-e を複数回使い、1p と $p の両方を指定します。",
    },

    # --- 4. アドレス指定 ---------------------------------------------
    {
        "id": 36, "category": "アドレス指定", "difficulty": 2,
        "title": "特定行を置換",
        "description": "2行目だけ \"old\" を \"new\" に置換してください。",
        "input": "old value\nold value\nold value\n",
        "answer": r"'2s/old/new/'",
        "hint": "行番号をコマンドの直前に書くと、その行だけに適用されます。",
    },
    {
        "id": 37, "category": "アドレス指定", "difficulty": 2,
        "title": "範囲指定して置換",
        "description": "2〜3行目だけ \"x\" を \"y\" に置換してください。",
        "input": "x\nx\nx\nx\n",
        "answer": r"'2,3s/x/y/'",
        "hint": "2,3 のように範囲を指定してからコマンドを書きます。",
    },
    {
        "id": 38, "category": "アドレス指定", "difficulty": 2,
        "title": "パターンで範囲を指定",
        "description": "\"START\" から \"END\" までの行（両方含む）を削除してください。",
        "input": "before\nSTART\nmiddle\nEND\nafter\n",
        "answer": r"'/START/,/END/d'",
        "hint": "/START/,/END/ のようにパターン同士で範囲を指定できます。",
    },
    {
        "id": 39, "category": "アドレス指定", "difficulty": 2,
        "title": "行番号とパターンの組み合わせ範囲",
        "description": "2行目から \"END\" が現れるまでの行を削除してください。",
        "input": "1\n2\nmiddle\nEND\n5\n",
        "answer": r"'2,/END/d'",
        "hint": "行番号,/pattern/ のように行番号とパターンを組み合わせた範囲も使えます。",
    },
    {
        "id": 40, "category": "アドレス指定", "difficulty": 2,
        "title": "最終行以外に処理",
        "description": "-n を使い、最終行以外のすべての行を表示してください（! を使う）。",
        "input": "a\nb\nc\n",
        "answer": r"-n '$!p'",
        "hint": "$! は「最終行ではない」という否定アドレスです。",
    },
    {
        "id": 41, "category": "アドレス指定", "difficulty": 2,
        "title": "特定行番号を除いて表示",
        "description": "-n を使い、2行目以外を表示してください。",
        "input": "1\n2\n3\n",
        "answer": r"-n '2!p'",
        "hint": "2! は「2行目ではない」という否定アドレスです。",
    },
    {
        "id": 42, "category": "アドレス指定", "difficulty": 2,
        "title": "ステップ指定での削除",
        "description": "1行目から3行おきに削除してください（1, 4, 7行目...を削除）。",
        "input": "1\n2\n3\n4\n5\n6\n7\n8\n",
        "answer": r"'1~3d'",
        "hint": "1~3 のようなステップアドレスは d にも使えます。",
    },
    {
        "id": 43, "category": "アドレス指定", "difficulty": 2,
        "title": "複数パターンのいずれか",
        "description": "\"ERROR\" または \"WARN\" を含む行だけを -n と p で表示してください（拡張正規表現 -E を使う）。",
        "input": "INFO a\nERROR b\nWARN c\nINFO d\n",
        "answer": r"-n -E '/ERROR|WARN/p'",
        "hint": "-E（拡張正規表現）を使うと | でOR条件を書けます。",
    },
    {
        "id": 44, "category": "アドレス指定", "difficulty": 2,
        "title": "行範囲＋パターンの否定",
        "description": "3行目以降で、\"skip\" を含む行を削除してください。",
        "input": "keep1\nkeep2\nskip1\nskip2\nkeep3\n",
        "answer": r"'3,${/skip/d}'",
        "hint": "addr1,addr2{command} のように範囲の中にさらに条件付きコマンドを書けます。",
    },
    {
        "id": 45, "category": "アドレス指定", "difficulty": 2,
        "title": "先頭行を除くインデント",
        "description": "先頭行を除くすべての行の行頭に、スペース2個のインデントを追加してください。",
        "input": "header\nrow1\nrow2\n",
        "answer": r"'1!s/^/  /'",
        "hint": "1! で1行目以外に絞り込めます。",
    },

    # --- 5. 正規表現 ---------------------------------------------------
    {
        "id": 46, "category": "正規表現", "difficulty": 3,
        "title": "任意の1文字 (.)",
        "description": "\"c.t\" のパターン（cとtの間に任意の1文字）にマッチする単語を \"MATCH\" に置き換えてください。",
        "input": "cat cot cut cost\n",
        "answer": r"'s/c.t/MATCH/g'",
        "hint": ". は任意の1文字にマッチします。",
    },
    {
        "id": 47, "category": "正規表現", "difficulty": 3,
        "title": "0回以上の繰り返し (*)",
        "description": "\"ab*c\"（aの後に0回以上のb、そしてc）にマッチする部分を \"X\" に置き換えてください。",
        "input": "ac abc abbc abbbc axc\n",
        "answer": r"'s/ab*c/X/g'",
        "hint": "* は直前の文字の0回以上の繰り返しです。",
    },
    {
        "id": 48, "category": "正規表現", "difficulty": 3,
        "title": "文字クラス",
        "description": "数字1文字を \"#\" に置き換えてください（すべて）。",
        "input": "a1b2c3\n",
        "answer": r"'s/[0-9]/#/g'",
        "hint": "[0-9] のような文字クラスで数字にマッチできます。",
    },
    {
        "id": 49, "category": "正規表現", "difficulty": 3,
        "title": "否定文字クラス",
        "description": "数字以外の文字をすべて \"_\" に置き換えてください。",
        "input": "a1b2c3\n",
        "answer": r"'s/[^0-9]/_/g'",
        "hint": "[^...] は否定の文字クラスです。",
    },
    {
        "id": 50, "category": "正規表現", "difficulty": 3,
        "title": "行頭アンカー",
        "description": "行が \"http\" で始まる場合だけ、その行全体を \"URL\" に置き換えてください。",
        "input": "http://example.com\nftp://example.com\n",
        "answer": r"'s/^http.*/URL/'",
        "hint": "^ は行頭、.* は任意の文字列（0文字以上）を表します。",
    },
    {
        "id": 51, "category": "正規表現", "difficulty": 3,
        "title": "行末アンカー",
        "description": "行末の \".txt\" を \".md\" に置き換えてください。",
        "input": "readme.txt\nnotes.txt\nimage.png\n",
        "answer": r"'s/\.txt$/.md/'",
        "hint": "$ は行末のアンカーです。ピリオドは \\. とエスケープします。",
    },
    {
        "id": 52, "category": "正規表現", "difficulty": 3,
        "title": "1回以上の繰り返し (\\+)",
        "description": "1個以上連続する数字を \"N\" に置き換えてください。",
        "input": "id42 code007 x\n",
        "answer": r"'s/[0-9]\+/N/g'",
        "hint": "\\+ は「1回以上」を表すGNU拡張です。",
    },
    {
        "id": 53, "category": "正規表現", "difficulty": 3,
        "title": "0回または1回 (\\?)",
        "description": "\"colou?r\"（colorまたはcolour）のパターンを \"COLOR\" に置き換えてください。",
        "input": "color colour colouur\n",
        "answer": r"'s/colou\?r/COLOR/g'",
        "hint": "\\? は「0回または1回」を表すGNU拡張です。",
    },
    {
        "id": 54, "category": "正規表現", "difficulty": 3,
        "title": "拡張正規表現でのOR (-E)",
        "description": "-E を使い、\"cat\" または \"dog\" を \"pet\" に置き換えてください。",
        "input": "cat and dog and bird\n",
        "answer": r"-E 's/cat|dog/pet/g'",
        "hint": "-E を使うと | がそのままORとして使えます（BREでは \\| が必要）。",
    },
    {
        "id": 55, "category": "正規表現", "difficulty": 3,
        "title": "拡張正規表現での量指定子 {n,m}",
        "description": "-E を使い、2〜3桁の数字を \"NUM\" に置き換えてください。",
        "input": "1 12 123\n",
        "answer": r"-E 's/[0-9]{2,3}/NUM/g'",
        "hint": "-E を使うと {n,m} がそのまま量指定子として使えます。",
    },
    {
        "id": 56, "category": "正規表現", "difficulty": 3,
        "title": "メタ文字のエスケープ",
        "description": "ピリオド \".\" をすべて \",\" に置き換えてください（正規表現のメタ文字ではなく、リテラルの点として扱う）。",
        "input": "1.2.3\n",
        "answer": r"'s/\./,/g'",
        "hint": "正規表現のメタ文字 . をリテラルとして使うには \\. とエスケープします。",
    },
    {
        "id": 57, "category": "正規表現", "difficulty": 3,
        "title": "単語境界 (\\b)",
        "description": "単語全体が \"cat\" である部分だけを \"dog\" に置き換えてください（\"category\" などは変えない）。",
        "input": "cat category concatenate cat\n",
        "answer": r"'s/\bcat\b/dog/g'",
        "hint": "\\b は単語境界にマッチするGNU拡張です。",
    },
    {
        "id": 58, "category": "正規表現", "difficulty": 3,
        "title": "括弧で囲まれた部分の削除",
        "description": "括弧 \"(...)\" で囲まれた最初の部分を削除してください（例: \"(abc) middle (def)\" → \" middle (def)\"）。",
        "input": "(abc) middle (def)\n",
        "answer": r"'s/([^)]*)//'",
        "hint": "BRE では ( と ) はグループ化ではなく、ただの文字として扱われます。",
    },
    {
        "id": 59, "category": "正規表現", "difficulty": 3,
        "title": "大文字への変換 (\\U)",
        "description": "GNU sedの拡張機能 \\U を使い、行全体を大文字に変換してください。",
        "input": "hello world\n",
        "answer": r"'s/.*/\U&/'",
        "hint": "\\U はそれ以降を大文字に変換するGNU拡張、& はマッチ全体です。",
    },
    {
        "id": 60, "category": "正規表現", "difficulty": 3,
        "title": "先頭文字だけ大文字化",
        "description": "GNU sedの拡張機能 \\u を使い、各行の先頭の文字だけを大文字にしてください。",
        "input": "hello\nworld\n",
        "answer": r"'s/^./\u&/'",
        "hint": "\\u は直後の1文字だけを大文字にするGNU拡張です。",
    },

    # --- 6. グループ参照 ------------------------------------------------
    {
        "id": 61, "category": "グループ参照", "difficulty": 3,
        "title": "キャプチャグループの基本",
        "description": "\"姓 名\" の順を \"名 姓\" の順に入れ替えてください。",
        "input": "Doe John\n",
        "answer": r"'s/\(.*\) \(.*\)/\2 \1/'",
        "hint": "\\( \\) でグループ化し、\\1 \\2 で参照します。",
    },
    {
        "id": 62, "category": "グループ参照", "difficulty": 3,
        "title": "日付フォーマットの変換",
        "description": "\"YYYY-MM-DD\" 形式の日付を \"DD/MM/YYYY\" 形式に変換してください。",
        "input": "2024-01-31\n",
        "answer": r"'s/\([0-9]\+\)-\([0-9]\+\)-\([0-9]\+\)/\3\/\2\/\1/'",
        "hint": "3つのグループに分けて、\\1 \\2 \\3 の順序を入れ替えます。",
    },
    {
        "id": 63, "category": "グループ参照", "difficulty": 3,
        "title": "重複する単語の圧縮",
        "description": "連続して重複する単語（例: \"the the\"）を1つにまとめてください。",
        "input": "the the quick fox fox jumps\n",
        "answer": r"'s/\([a-z]\+\) \1/\1/g'",
        "hint": "同じ単語が続くパターンを \\(...\\) \\1 のように書きます。",
    },
    {
        "id": 64, "category": "グループ参照", "difficulty": 3,
        "title": "キャプチャを使った抽出",
        "description": "括弧内の数字だけを取り出し、それ以外を削除してください（例: \"value(42)\" → \"42\"）。",
        "input": "value(42)\n",
        "answer": r"'s/.*(\([0-9]\+\)).*/\1/'",
        "hint": ".* で不要な部分を貪欲にマッチさせつつ、必要な部分だけグループ化します。",
    },
    {
        "id": 65, "category": "グループ参照", "difficulty": 3,
        "title": "拡張正規表現でのグループ参照",
        "description": "-E を使い、\"key=value\" の形式を \"value=key\" に入れ替えてください。",
        "input": "name=Alice\n",
        "answer": r"-E 's/(.*)=(.*)/\2=\1/'",
        "hint": "-E では \\( \\) の代わりに ( ) がそのままグループ化に使えます。",
    },
    {
        "id": 66, "category": "グループ参照", "difficulty": 3,
        "title": "3桁ごとの桁区切り (簡易版)",
        "description": "6桁の数字に、末尾から3桁ごとにカンマを挿入してください（例: \"123456\" → \"123,456\"）。",
        "input": "123456\n",
        "answer": r"'s/\([0-9]\+\)\([0-9]\{3\}\)$/\1,\2/'",
        "hint": "末尾3桁とそれ以前を分けてグループ化します。",
    },
    {
        "id": 67, "category": "グループ参照", "difficulty": 3,
        "title": "CSVの列を入れ替え",
        "description": "カンマ区切りの3列 \"a,b,c\" を \"c,b,a\" の順に入れ替えてください。",
        "input": "one,two,three\n",
        "answer": r"'s/\([^,]*\),\([^,]*\),\([^,]*\)/\3,\2,\1/'",
        "hint": "[^,]* でカンマを含まない部分にマッチさせます。",
    },
    {
        "id": 68, "category": "グループ参照", "difficulty": 3,
        "title": "HTMLタグの除去",
        "description": "\"<...>\" のタグをすべて削除してください。",
        "input": "<b>hello</b> <i>world</i>\n",
        "answer": r"'s/<[^>]*>//g'",
        "hint": "<[^>]*> でタグ全体にマッチさせ、空文字に置換します。",
    },
    {
        "id": 69, "category": "グループ参照", "difficulty": 3,
        "title": "引用符で囲まれた部分の抽出",
        "description": "ダブルクォートで囲まれた最初の文字列だけを残し、それ以外を削除してください。",
        "input": "log: \"important message\" end\n",
        "answer": r"""'s/.*"\([^"]*\)".*/\1/'""",
        "hint": "最初と最後のダブルクォートの間を \\([^\"]*\\) でキャプチャします。",
    },
    {
        "id": 70, "category": "グループ参照", "difficulty": 3,
        "title": "& とグループの組み合わせ",
        "description": "数字にマッチした部分をかっこで囲んでください（例: \"42\" → \"(42)\"）。",
        "input": "id 42 code 7\n",
        "answer": r"'s/[0-9]\+/(&)/g'",
        "hint": "& を () で囲む形の置換に使います。",
    },
    {
        "id": 71, "category": "グループ参照", "difficulty": 3,
        "title": "同じ文字の3連続を検出",
        "description": "同じ文字が3回連続している箇所を \"***\" に置き換えてください。",
        "input": "aaa bbb abc\n",
        "answer": r"'s/\(.\)\1\1/***/g'",
        "hint": "\\(.\\)\\1\\1 で同じ文字が3回続く箇所を検出します。",
    },
    {
        "id": 72, "category": "グループ参照", "difficulty": 3,
        "title": "拡張正規表現の量指定子とグループ",
        "description": "-E を使い、1回以上繰り返す \"ab\" を1つの \"ab\" にまとめてください（例: \"abababab\" → \"ab\"）。",
        "input": "abababab xyz\n",
        "answer": r"-E 's/(ab)+/ab/g'",
        "hint": "-E の (ab)+ のようにグループに + を付けられます。",
    },
    {
        "id": 73, "category": "グループ参照", "difficulty": 3,
        "title": "先頭と末尾の文字を入れ替え",
        "description": "先頭の文字と末尾の文字を入れ替えてください（例: \"hello\" → \"oellh\"）。",
        "input": "hello\n",
        "answer": r"'s/^\(.\)\(.*\)\(.\)$/\3\2\1/'",
        "hint": "先頭1文字・中間・末尾1文字の3グループに分けます。",
    },
    {
        "id": 74, "category": "グループ参照", "difficulty": 3,
        "title": "電話番号のフォーマット",
        "description": "\"09012345678\" のような11桁の電話番号を \"090-1234-5678\" の形式に変換してください。",
        "input": "09012345678\n",
        "answer": r"'s/\([0-9]\{3\}\)\([0-9]\{4\}\)\([0-9]\{4\}\)/\1-\2-\3/'",
        "hint": "3桁・4桁・4桁の3グループに分けてハイフンで結合します。",
    },
    {
        "id": 75, "category": "グループ参照", "difficulty": 3,
        "title": "メールアドレスのドメイン部分を抽出",
        "description": "メールアドレスからドメイン部分だけを取り出してください（例: \"user@example.com\" → \"example.com\"）。",
        "input": "user@example.com\n",
        "answer": r"'s/.*@\(.*\)/\1/'",
        "hint": "@ より後ろを \\(...\\) でキャプチャします。",
    },

    # --- 7. 複数行処理 ---------------------------------------------------
    {
        "id": 76, "category": "複数行処理", "difficulty": 4,
        "title": "次の行を結合 (N)",
        "description": "N コマンドを使い、1行目と2行目を1行にスペースで結合してください。",
        "input": "hello\nworld\n",
        "answer": r"'N;s/\n/ /'",
        "hint": "N で次の行をパターンスペースに読み込み、間の改行を置換します。",
    },
    {
        "id": 77, "category": "複数行処理", "difficulty": 4,
        "title": "3行を1行に結合",
        "description": "N を2回使い、3行を1つのスペース区切りの行にまとめてください。",
        "input": "a\nb\nc\n",
        "answer": r"'N;N;s/\n/ /g'",
        "hint": "N を2回使うと3行分をまとめて扱えます。",
    },
    {
        "id": 78, "category": "複数行処理", "difficulty": 4,
        "title": "連続する空行を1つに圧縮",
        "description": "連続する空行を1つの空行にまとめてください。",
        "input": "a\n\n\n\nb\n",
        "answer": r"'/^$/{N;/^\n$/D}'",
        "hint": "空行の後にもう一度Nして、2行とも空ならDでやり直す、という古典的手法です。",
    },
    {
        "id": 79, "category": "複数行処理", "difficulty": 4,
        "title": "スライディングウィンドウの基本形",
        "description": "$!N;P;D のパターンを実行し、結果を確認してください（結果は入力と同じになります）。",
        "input": "1\n2\n3\n",
        "answer": r"'$!N;P;D'",
        "hint": "$!N;P;D は多くの複数行処理の基本形（スライディングウィンドウ）です。",
    },
    {
        "id": 80, "category": "複数行処理", "difficulty": 4,
        "title": "ホールドスペースで各行を2回出力",
        "description": "h と G を使い、各行を2回連続で出力してください。",
        "input": "x\ny\n",
        "answer": r"'h;G'",
        "hint": "h でホールドスペースにコピーし、G でホールドスペースをパターンスペースに追加します。",
    },
    {
        "id": 81, "category": "複数行処理", "difficulty": 4,
        "title": "行を逆順にする (tac相当)",
        "description": "入力の行順序を逆にしてください。",
        "input": "1\n2\n3\n4\n",
        "answer": r"'1!G;h;$!d'",
        "hint": "1!G;h;$!d は行を逆順にする有名な定型句です。",
    },
    {
        "id": 82, "category": "複数行処理", "difficulty": 4,
        "title": "隣接する重複行の圧縮 (uniq相当)",
        "description": "隣接する重複行を1つにまとめてください。",
        "input": "a\na\nb\nb\nb\nc\n",
        "answer": r"'$!N;/^\(.*\)\n\1$/!P;D'",
        "hint": "$!N;/^\\(.*\\)\\n\\1$/!P;D は隣接する重複行をまとめる定型句です。",
    },
    {
        "id": 83, "category": "複数行処理", "difficulty": 4,
        "title": "奇数行だけを残す (nとd)",
        "description": "n と d を使い、奇数行だけを残し、偶数行を取り除いてください。",
        "input": "1\n2\n3\n4\n5\n6\n",
        "answer": r"'n;d'",
        "hint": "n で次の行を読み込み、d で今の行を消すことで交互に処理します。",
    },
    {
        "id": 84, "category": "複数行処理", "difficulty": 4,
        "title": "行番号を出力 (=)",
        "description": "= コマンドを使い、各行の直前にその行番号を別の行として出力してください。",
        "input": "apple\nbanana\n",
        "answer": r"'='",
        "hint": "= コマンドは行番号だけを別行として出力します。",
    },
    {
        "id": 85, "category": "複数行処理", "difficulty": 4,
        "title": "各行の後に空行を挿入 (ダブルスペース)",
        "description": "G コマンドだけを使い、各行の後に空行を挿入してください。",
        "input": "a\nb\nc\n",
        "answer": r"'G'",
        "hint": "G だけでホールドスペース（初期状態は空）を追加すると空行が挿入されます。",
    },
    {
        "id": 86, "category": "複数行処理", "difficulty": 4,
        "title": "総行数を数える (wc -l相当)",
        "description": "-n と $= を使い、入力の総行数だけを出力してください。",
        "input": "a\nb\nc\nd\n",
        "answer": r"-n '$='",
        "hint": "-n と $= を組み合わせると、最終行でだけ行番号（=総行数）を表示できます。",
    },
    {
        "id": 87, "category": "複数行処理", "difficulty": 4,
        "title": "最初と最後の行を除いて表示",
        "description": "-n を使い、最初の行と最後の行を除いたすべての行を表示してください。",
        "input": "first\nmid1\nmid2\nlast\n",
        "answer": r"-n -e '1!{$!p}'",
        "hint": "1!{$!p} は「1行目でも最終行でもない」行だけを選びます。",
    },
    {
        "id": 88, "category": "複数行処理", "difficulty": 4,
        "title": "特定行の後に行を追加 (a コマンド)",
        "description": "a コマンドを使い、2行目の直後に \"-- inserted --\" という行を追加してください。",
        "input": "line1\nline2\nline3\n",
        "answer": r"'2a -- inserted --'",
        "hint": "a コマンドはその行の後に新しい行を追加します。",
    },
    {
        "id": 89, "category": "複数行処理", "difficulty": 4,
        "title": "特定行の前に行を挿入 (i コマンド)",
        "description": "i コマンドを使い、3行目の直前に \"--- 区切り ---\" という行を挿入してください。",
        "input": "1\n2\n3\n4\n",
        "answer": r"'3i --- 区切り ---'",
        "hint": "i コマンドはその行の前に新しい行を挿入します。",
    },
    {
        "id": 90, "category": "複数行処理", "difficulty": 4,
        "title": "行の置き換え (c コマンド)",
        "description": "c コマンドを使い、2行目を丸ごと \"REPLACED\" という行に置き換えてください。",
        "input": "1\n2\n3\n",
        "answer": r"'2c REPLACED'",
        "hint": "c コマンドは行の内容をまるごと置き換えます。",
    },

    # --- 8. 分岐・応用 ----------------------------------------------------
    {
        "id": 91, "category": "分岐・応用", "difficulty": 5,
        "title": "文字変換 (y コマンド)",
        "description": "y コマンドを使い、小文字のアルファベットをすべて大文字に変換してください。",
        "input": "hello world\n",
        "answer": r"'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'",
        "hint": "y/元の文字/変換後の文字/ で1文字ずつ変換します（正規表現ではありません）。",
    },
    {
        "id": 92, "category": "分岐・応用", "difficulty": 5,
        "title": "ROT13変換",
        "description": "y コマンドを使い、ROT13変換（アルファベットを13文字シフト）を行ってください。",
        "input": "hello\n",
        "answer": r"'y/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/nopqrstuvwxyzabcdefghijklmNOPQRSTUVWXYZABCDEFGHIJKLM/'",
        "hint": "y コマンドで26文字すべての対応表を書き出します。",
    },
    {
        "id": 93, "category": "分岐・応用", "difficulty": 5,
        "title": "ラベルとtによる繰り返し置換",
        "description": ":ラベル と t（分岐）を使い、連続するスペースが無くなるまで2個ずつ1個に圧縮してください。",
        "input": "a          b\n",
        "answer": r"':a;s/  / /;ta'",
        "hint": ":でラベルを付け、tで直前のsが成功した場合だけ繰り返し処理（ループ）します。",
    },
    {
        "id": 94, "category": "分岐・応用", "difficulty": 5,
        "title": "tコマンドで一致した場合のみ処理",
        "description": "\"foo\" を \"bar\" に置換できた行だけ、さらに末尾に \" [changed]\" を追記してください。置換できなかった行はそのままにしてください。",
        "input": "foo baz\nqux quux\n",
        "answer": r"'s/foo/bar/;ta;b;:a;s/$/ [changed]/'",
        "hint": "t は直前の s が成功した場合だけ分岐するコマンドです。b は無条件でジャンプ（ラベルなしなら末尾）します。",
    },
    {
        "id": 95, "category": "分岐・応用", "difficulty": 5,
        "title": "偶数行にだけ印を付ける (n)",
        "description": "n コマンドを使い、奇数行はそのまま、偶数行だけ末尾に \"!\" を追加してください。",
        "input": "a\nb\nc\nd\n",
        "answer": r"'n;s/$/!/'",
        "hint": "n は次の行を読み込むコマンドです（Nとは違い、直前の内容は自動出力されます）。",
    },
    {
        "id": 96, "category": "分岐・応用", "difficulty": 5,
        "title": "全行を1行に結合するループ",
        "description": ":ラベル と N, b を使い、ファイル全体をスペース区切りの1行に結合してください。",
        "input": "a\nb\nc\nd\n",
        "answer": r"':a;N;$!ba;s/\n/ /g'",
        "hint": ":a;N;$!ba という形で最終行になるまでNを繰り返すループです。",
    },
    {
        "id": 97, "category": "分岐・応用", "difficulty": 5,
        "title": "コメントと空行を除去して整形",
        "description": "\"#\" から始まるコメント行と空行を削除し、さらに各行前後の余分な空白を取り除いてください。",
        "input": "# comment\n  value1  \n\n# another\nvalue2\n\n",
        "answer": r"-e '/^#/d' -e '/^[[:space:]]*$/d' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'",
        "hint": "-e を複数回組み合わせて、複数の条件を順に適用します。",
    },

    # --- 9. 総合問題 -------------------------------------------------------
    {
        "id": 98, "category": "総合問題", "difficulty": 5,
        "title": "ログからエラーだけ抽出して整形",
        "description": "各行が \"LEVEL: message\" 形式のログから \"ERROR\" 行だけを抽出し、\"LEVEL: \" の部分を削除してメッセージだけを表示してください。",
        "input": "INFO: start\nERROR: disk full\nINFO: continue\nERROR: timeout\n",
        "answer": r"-n -e '/^ERROR/s/^ERROR: //p'",
        "hint": "-n と、パターンに一致した行だけに置換+pを行うテクニックを組み合わせます。",
    },
    {
        "id": 99, "category": "総合問題", "difficulty": 5,
        "title": "CSVをTSVに変換し先頭行を除去",
        "description": "CSV形式の入力からヘッダー行（1行目）を除去し、カンマをタブに変換してください。",
        "input": "name,age,city\nAlice,30,Tokyo\nBob,25,Osaka\n",
        "answer": r"-e '1d' -e 's/,/\t/g'",
        "hint": "1d でヘッダー行を消し、カンマをタブ(\\t)に置換します。",
    },
    {
        "id": 100, "category": "総合問題", "difficulty": 5,
        "title": "設定ファイルの整形",
        "description": "設定ファイル風のテキストから、コメント行・空行を削除し、\"key = value\" の空白を詰めて \"key=value\" に統一してください。",
        "input": "# config file\n\nname = value1\n\nport   =   8080\n# end\ntimeout=30\n",
        "answer": r"-e '/^#/d' -e '/^$/d' -e 's/ *= */=/'",
        "hint": "= の前後の空白をまとめて詰める正規表現を書きます。",
    },
]
